force-app/main/default/objects/Account/recordTypes/Supplier.recordType-meta.xml
<RecordType>
    <fullName>Supplier</fullName>
    <active>true</active>
    <businessProcess>Master</businessProcess>
    <label>サプライヤー</label>
</RecordType>

force-app/main/default/objects/Corrective_Action__c/Corrective_Action__c.object-meta.xml
<CustomObject>
    <label>是正処置</label>
    <nameField>
        <displayFormat>CA-{0000}</displayFormat>
        <label>是正処置番号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>是正処置</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Corrective_Action__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>原因サプライヤー</label>
    <type>Lookup</type>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>是正処置（原因サプライヤー）</relationshipLabel>
    <relationshipName>Corrective_Actions_Supplier</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/Manufacturing_Site__c/Manufacturing_Site__c.object-meta.xml
<CustomObject>
    <label>製造拠点</label>
    <pluralLabel>製造拠点</pluralLabel>
    <nameField>
        <label>拠点名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Manufacturing_Site__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>サプライヤー</label>
    <type>Lookup</type>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>製造拠点</relationshipLabel>
    <relationshipName>Manufacturing_Sites</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/RFQ__c/RFQ__c.object-meta.xml
<CustomObject>
    <label>購買見積依頼</label>
    <nameField>
        <displayFormat>RFQ-{0000}</displayFormat>
        <label>購買見積依頼番号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>購買見積依頼</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/RFQ_Quote__c/RFQ_Quote__c.object-meta.xml
<CustomObject>
    <label>購買見積回答</label>
    <nameField>
        <displayFormat>QT-{0000}</displayFormat>
        <label>購買見積回答番号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>購買見積回答</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/RFQ_Quote__c/fields/Manufacturing_Site__c.field-meta.xml
<CustomField>
    <fullName>Manufacturing_Site__c</fullName>
    <label>製造拠点</label>
    <type>Lookup</type>
    <referenceTo>Manufacturing_Site__c</referenceTo>
    <relationshipLabel>見積回答</relationshipLabel>
    <relationshipName>RFQ_Quotes</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/RFQ_Quote__c/fields/RFQ__c.field-meta.xml
<CustomField>
    <fullName>RFQ__c</fullName>
    <label>見積依頼</label>
    <type>MasterDetail</type>
    <referenceTo>RFQ__c</referenceTo>
    <relationshipLabel>見積回答</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
</CustomField>

force-app/main/default/objects/RFQ_Quote__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>サプライヤー</label>
    <type>Lookup</type>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>見積回答</relationshipLabel>
    <relationshipName>RFQ_Quotes</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/Supplier_Certification__c/Supplier_Certification__c.object-meta.xml
<CustomObject>
    <label>サプライヤー認証</label>
    <pluralLabel>サプライヤー認証</pluralLabel>
    <nameField>
        <label>認証番号</label>
        <type>AutoNumber</type>
        <displayFormat>CERT-{0000}</displayFormat>
        <startingNumber>1</startingNumber>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Certification__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>サプライヤー</label>
    <type>Lookup</type>
    <referenceTo>Account</referenceTo>
    <relationshipName>Supplier_Certifications</relationshipName>
    <relationshipLabel>サプライヤー認証</relationshipLabel>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/Supplier_Investigation__c/Supplier_Investigation__c.object-meta.xml
<CustomObject>
    <label>サプライヤー調査</label>
    <nameField>
        <displayFormat>SI-{0000}</displayFormat>
        <label>サプライヤー調査番号</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>サプライヤー調査</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Supplier_Investigation__c/fields/Corrective_Action__c.field-meta.xml
<CustomField>
    <fullName>Corrective_Action__c</fullName>
    <label>是正処置</label>
    <type>Lookup</type>
    <referenceTo>Corrective_Action__c</referenceTo>
    <relationshipLabel>サプライヤー調査</relationshipLabel>
    <relationshipName>Supplier_Investigations</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/objects/Supplier_Investigation__c/fields/Supplier__c.field-meta.xml
<CustomField>
    <fullName>Supplier__c</fullName>
    <label>サプライヤー</label>
    <type>Lookup</type>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>サプライヤー調査</relationshipLabel>
    <relationshipName>Supplier_Investigations</relationshipName>
    <deleteConstraint>SetNull</deleteConstraint>
</CustomField>

force-app/main/default/classes/SupplierPortalSharingTest.cls
/**
 * SRMサプライヤーポータルのSharingSet/外部OWDが期待通り動作するかを検証する。
 * runAs()でPartner Community Userとして実行し、自Accountのレコードのみ見えることを確認する。
 */
@IsTest(SeeAllData=true)
private class SupplierPortalSharingTest {

    @IsTest
    static void portalUserCanSeeOwnSupplierDataOnly() {
        User portalUser = [
            SELECT Id, Username, AccountId
            FROM User
            WHERE Username = 'yoshida1776431632685@greenenergy.demo.sfdc'
            LIMIT 1
        ];
        System.assertNotEquals(null, portalUser.AccountId, 'PortalユーザーにAccountIdが必要');

        Id ownAccountId = portalUser.AccountId;

        // 他社サプライヤー: 吉田のAccount以外
        Id otherSupplierId = [
            SELECT Id FROM Account
            WHERE RecordType.DeveloperName = 'Supplier' AND Id != :ownAccountId
            LIMIT 1
        ].Id;

        Test.startTest();
        System.runAs(portalUser) {
            // Manufacturing_Site__c: 自社のみ見える
            Integer ownSites = [SELECT COUNT() FROM Manufacturing_Site__c WHERE Supplier__c = :ownAccountId];
            Integer otherSites = [SELECT COUNT() FROM Manufacturing_Site__c WHERE Supplier__c = :otherSupplierId];
            System.debug(LoggingLevel.INFO, '[Manufacturing_Site__c] own=' + ownSites + ' other=' + otherSites);
            System.assert(ownSites > 0, '自社のManufacturing_Siteが見えるべき');
            System.assertEquals(0, otherSites, '他社のManufacturing_Siteは見えてはいけない');

            // Supplier_Certification__c: 自社のみ
            Integer ownCerts = [SELECT COUNT() FROM Supplier_Certification__c WHERE Supplier__c = :ownAccountId];
            Integer otherCerts = [SELECT COUNT() FROM Supplier_Certification__c WHERE Supplier__c = :otherSupplierId];
            System.debug(LoggingLevel.INFO, '[Supplier_Certification__c] own=' + ownCerts + ' other=' + otherCerts);
            System.assertEquals(0, otherCerts, '他社のCertificationは見えてはいけない');

            // Corrective_Action__c: 自社のみ
            Integer ownCAs = [SELECT COUNT() FROM Corrective_Action__c WHERE Supplier__c = :ownAccountId];
            Integer otherCAs = [SELECT COUNT() FROM Corrective_Action__c WHERE Supplier__c = :otherSupplierId];
            System.debug(LoggingLevel.INFO, '[Corrective_Action__c] own=' + ownCAs + ' other=' + otherCAs);
            System.assertEquals(0, otherCAs, '他社のCorrectiveActionは見えてはいけない');

            // Supplier_Investigation__c (Corrective_ActionのChild): 自社のみ
            Integer ownSIs = [
                SELECT COUNT() FROM Supplier_Investigation__c
                WHERE Corrective_Action__r.Supplier__c = :ownAccountId
            ];
            Integer otherSIs = [
                SELECT COUNT() FROM Supplier_Investigation__c
                WHERE Corrective_Action__r.Supplier__c = :otherSupplierId
            ];
            System.debug(LoggingLevel.INFO, '[Supplier_Investigation__c] own=' + ownSIs + ' other=' + otherSIs);
            System.assertEquals(0, otherSIs, '他社のInvestigationは見えてはいけない');

            // RFQ__c: Public Read -> 全件見える
            Integer allRfqs = [SELECT COUNT() FROM RFQ__c];
            System.debug(LoggingLevel.INFO, '[RFQ__c] all visible=' + allRfqs);
            System.assert(allRfqs > 0, 'RFQ__cはPublic Readなので全件見えるべき');

            // RFQ_Quote__c (RFQのChild): 自社宛のみ見える（※実際にはChildなのでPublic Read継承だが、RFQが親なのでQuoteも同様に見える）
            Integer ownQuotes = [SELECT COUNT() FROM RFQ_Quote__c WHERE Supplier__c = :ownAccountId];
            System.debug(LoggingLevel.INFO, '[RFQ_Quote__c] own=' + ownQuotes);

            // SupplierPortalController.getDashboard 呼び出し検証
            SupplierPortalController.DashboardDTO dto = SupplierPortalController.getDashboard(ownAccountId);
            System.assertNotEquals(null, dto, 'DashboardDTOが返ってくるべき');
            System.assertNotEquals(null, dto.supplier, 'Supplier情報が返ってくるべき');
            System.debug(LoggingLevel.INFO, '[Dashboard] supplier=' + dto.supplier.name
                + ' recentRfqs=' + (dto.recentRfqs == null ? 0 : dto.recentRfqs.size())
                + ' recentInvestigations=' + (dto.recentInvestigations == null ? 0 : dto.recentInvestigations.size()));
        }
        Test.stopTest();
    }
}